language: java
branches:
  only:
    - develop
    - master
    - "/release-[0-999].[0-999]$/"
#notifications:
#  email:
#    recipients:
#      - sergio.gsanchez97@gmail.com
env:
  - TAG=1.0
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR
  - docker build -t tronxi/coding-test-ranking:$TAG .
  - docker login  --username tronxi --password $DOCKER
  - docker push tronxi/coding-test-ranking:$TAG
#jobs:
#  include:
#    - stage: test
#      script: mvn install
#    - stage: sonar
#      script: mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tronxi -Dsonar.login=$SONAR_CODING
#    - stage: push
#      script:
#        - docker build -t tronxi/coding-test-ranking:$TAG .
#        - docker login  --username tronxi --password $DOCKER
#        - docker push tronxi/coding-test-ranking:$TAG