language: java
branches:
  only:
    - develop
    - master
    - "/release-[0-999].[0-999]$/"
env:
  - TAG=1.0
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR
  - docker build -t tronxi/coding-test-ranking:$TAG .
  - docker login  --username tronxi --password $DOCKER
  - docker push tronxi/coding-test-ranking:$TAG