version: '3'
services:
  ad-ranking-challenge:
    container_name: ad-ranking-challenge
    image: ad-ranking-challenge
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - ad-ranking-challenge

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ad-ranking-challenge

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ad-ranking-challenge

networks:
  ad-ranking-challenge: